name: Deploy to Azure Web App

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # Azure登录认证
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 构建并推送Docker镜像
    - name: Build and push image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build Docker image
      run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

    # 部署到Azure Web App
    - name: Update Web App Container
      run: |
        az webapp config container set \
          --name web-appsrv \
          --resource-group TestGroup \
          --docker-custom-image-name ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }} \
          --docker-registry-server-url https://${{ secrets.REGISTRY_LOGIN_SERVER }} \
          --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} \
          --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}